# Generated by Django 4.2.1 on 2023-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HEADMAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hrealy', models.DateField(verbose_name='Действительно до')),
                ('Hitem', models.CharField(max_length=25, verbose_name='Предмет')),
                ('Hexercise', models.TextField(verbose_name='Задание')),
                ('Hdata', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trealy', models.DateField(verbose_name='Действительно до')),
                ('Tmessage', models.TextField(verbose_name='Сообщение')),
                ('Tdata', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
