# Generated by Django 4.2.1 on 2023-05-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headman',
            options={'verbose_name': 'Домашняя работа', 'verbose_name_plural': 'Домашняя работа'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
